package caculators;

import java.util.ArrayList;

import entities.Movie;

/**
 * Helps calculte total Sales for movies
 */
public class SalesCalculator {
    /**
     * the single instance for this Class
     */
    private static SalesCalculator single_instance = null;

    /**
     * The Constructor for SalesCalculator
     */
    private SalesCalculator(){}

    /**
     * get an instance of the this class
     * @return SalesCalculator object
     */
    public static SalesCalculator getInstance(){
        if(single_instance == null){
            single_instance = new SalesCalculator();
        }
        return single_instance;
    }
    
    /**
     * calculate the total sales generated by movies
     * @param movies the movies to use for the calculation
     * @return the total sales generated by the movies
     */
    public double calc(ArrayList<Movie> movies){
        double total = 0;
        for(int i=0; i<movies.size(); i++){
            total += movies.get(i).getTotalSales();
        }
        return total;
    }
}
